//  Bill
export const ADD_BILL_COUPON = 'ADD_BILL_COUPON'
export const REMOVE_BILL_COUPON = 'REMOVE_BILL_COUPON'
export const SET_BILL_TOTAL = 'SET_BILL_TOTAL'
// Coupon
export const FETCH_COUPONS_SUCCESS = 'FETCH_COUPONS_SUCCESS'
export const ADD_COUPON_START = 'ADD_COUPON_START'
export const ADD_COUPON_SUCCESS = 'ADD_COUPON_SUCCESS'
export const ADD_COUPON_FAILURE = 'ADD_COUPON_FAILURE'
export const REMOVE_COUPON = 'REMOVE_COUPON'
export const UPDATE_COUPON = 'UPDATE_COUPON'